- name: Deploy DR Infra
  hosts: localhost
  connection: local
  gather_facts: no
  ####
  tasks:
    # -----------------------------
    # Validate environment variable FIRST
    # (prevents accidental prod backup to non-prod buckets)
    # -----------------------------
    - name: Validate environment variable
      assert:
        that:
          - env is defined
          - env in ['dev', 'test', 'prod']
        fail_msg: "env variable is missing or invalid"

    - name: Show environment
      debug:
        msg: "Running in environment: {{ env }}"

    - name: Run Terraform
      community.general.terraform:
        project_path: "./terraform"
        state: present
        force_init: true
        backend_config:
          bucket: "{{ 'dr-terraform-state-storage' if env == 'prod' else 'dr-terraform-state-storage-test' }}"
          key: "dr-infra/terraform.tfstate"
          region: "ap-south-1"
          dynamodb_table: "terraform-lock"
        variables:
          environment: "{{ env }}"
      register: tf_output
      environment:
        TF_IN_AUTOMATION: "true"
        TF_INPUT: "false"

    - name: Get DC IP
      command: terraform output -raw dc_public_ip
      args:
        chdir: "./terraform"
      register: dc_ip

    - name: Get Web IP
      command: terraform output -raw web_public_ip
      args:
        chdir: "./terraform"
      register: web_ip

    - name: Show DC IP
      debug:
        msg: "DC Private IP: {{ dc_private_ip.stdout }}"

    - name: Show Web IP
      debug:
        msg: "Web Public IP: {{ web_public_ip.stdout }}"

    - name: Pass IPs to next workflow
      set_stats:
        data:
          dc_host: "{{ dc_private_ip.stdout }}"
          web_host: "{{ web_public_ip.stdout }}"
