- name: Deploy DR Infra
  hosts: localhost
  connection: local
  gather_facts: no
  ####
  tasks:
    # -----------------------------
    # Validate environment variable FIRST
    # (prevents accidental prod backup to non-prod buckets)
    # -----------------------------
    - name: Validate environment variable
      assert:
        that:
          - env is defined
          - env in ['dev', 'test', 'prod']
        fail_msg: "env variable is missing or invalid"

    - name: Show environment
      debug:
        msg: "Running in environment: {{ env }}"
        
    - name: Run Terraform
      community.general.terraform:
        project_path: "./terraform"
        state: present
        force_init: true
        backend_config:
          bucket: "{{ 'dr-terraform-state-storage' if env == 'prod' else 'dr-terraform-state-storage-test' }}"
          key: "dr-infra/terraform.tfstate"
          region: "ap-south-1"
          dynamodb_table: "terraform-lock"
        variables:
          environment: "{{ env }}"
      register: tf_output
      environment:
        TF_IN_AUTOMATION: "true"
        TF_INPUT: "false"

    - name: Get EC2 IP
      command: terraform output -raw ec2_public_ip
      args:
        chdir: "./terraform"
      register: ec2_ip

    - name: Show EC2 IP
      debug:
        msg: "EC2 Public IP: {{ ec2_ip.stdout }}"

    - name: Pass EC2 IP to next job
      set_stats:
        data:
          target_host: "{{ ec2_ip.stdout }}"
